/* Copyright © 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */package cn.zhuatech.syntheticdata.repository;import cn.zhuatech.syntheticdata.model.GenerationAudit;import org.springframework.data.jpa.repository.JpaRepository;import java.util.*;/**
                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                     */
public interface GenerationAuditRepository extends JpaRepository<GenerationAudit,Long>{/**
                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                            */
Optional<GenerationAudit>findByRequestId(String id);/**
                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                */
List<GenerationAudit>findTop100ByOrderByCreatedAtDesc();}
