/* Copyright © 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */package cn.zhuatech.syntheticdata.controller;import cn.zhuatech.syntheticdata.common.ApiResponse;import cn.zhuatech.syntheticdata.model.GenerationAudit;import cn.zhuatech.syntheticdata.service.SyntheticDataService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@RestController@RequestMapping("/api/synthetic-data")public class SyntheticDataController{private final SyntheticDataService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public SyntheticDataController(SyntheticDataService s){service=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/generate")@PreAuthorize("hasAnyRole('ADMIN','DATA_ENGINEER')")public ApiResponse<SyntheticDataService.GenerationResult>generate(@Valid@RequestBody SyntheticDataService.GenerationRequest r,Authentication a){return ApiResponse.ok("合成数据生成完成",service.generate(r,a.getName()));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@GetMapping("/audits")@PreAuthorize("hasAnyRole('ADMIN','AUDITOR')")public ApiResponse<List<GenerationAudit>>audits(){return ApiResponse.ok("审计查询成功",service.audits());}}
